sudo: false
language: node_js
node_js:
  - "9"
  - "10"
  - "lts/*"
env:
  - TEST_SUITE=unit
matrix:
    include:
        - node_js: "lts/*"
          env: TEST_SUITE=lint
script: "npm run-script $TEST_SUITE"
